### ISSUE TITLE
Add configuration file support

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#195]
```toml
# global flags which will affect all commands and can be 
# overwritten by cli arguments.
[global]
skip-invalid = true

# section for each command, overwrites flags from [global]
# and will be overwritten by cli arguments.
[cat]
skip-invalid = false
```
